### ISSUE TITLE
Question about "new_d" argument in "predict"

### ISSUE THREAD

**Issue by RightHandOfDoom** [franzmohr/bvartools#4]
Hello!
I have a question about the "new_d" argument in the "predict()" function. The example is unfortunately not very clear to me.
The example dataset e1 has three variables (invest, income, cons) but "new_d" has only one row. How can the function identify for which variable this vector represents deterministic terms?
What if, for example I wanted to provide 10 new datapoints for "income", while predicting the other two variables?
What if I have data for both cons and income, for example? How would I have to change the argument "new_d" in this case? I hope my understanding is not too wrong.
Thank you very much for your help!

**Comment by franzmohr** [comment]
Hi! Sorry for the late response. new_d is for deterministic variables only, as new_x is only for other exogenous variables. Unfortunatly, the function does not support overwriting endogeneous variables yet, but I will try to accomodate this in the future. Best Franz
